version: '3'

services:
  worker:
    container_name: worker
    image: python:3
    working_dir: /usr/src/app
    volumes:
      - '../git-config:/root/.ssh'
      - 'workdir:/tmp/mlcycle'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '.:/usr/src/app'
    environment:
      - PYTHONUNBUFFERED=1
      - MLCYCLE_VOLUME=worker_workdir
      - MLCYCLE_WORKDIR=/tmp/mlcycle
      - MLCYCLE_RUNTIME=
      - MLCYCLE_HOST=https://cems-mbp.dhcp.fh-bielefeld.de:5001/api
      - MLCYCLE_PROJECT=
      - MLCYCLE_JOB=
      - MLCYCLE_STEP=
    restart: always
    command: /bin/bash -c "pip install -r requirements.txt && python run.py"
volumes:
  workdir: