version: '3'

services:
  worker-dev:
    container_name: worker.dev
    image: python:3
    working_dir: /usr/src/app
    volumes:
      - '../git-config:/root/.ssh'
      - 'workdir:/tmp/contiflow'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '.:/usr/src/app'
      - '../pyclientlib/:/usr/src/libs/pyclientlib'
    environment:
      - CONTIFLOW_RUNTIME=
      - CONTIFLOW_VOLUME=worker_workdir
      - CONTIFLOW_WORKDIR=/tmp/contiflow
      - CONTIFLOW_HOST=https://monster:5001
      - CONTIFLOW_PROJECT=
      - CONTIFLOW_JOB=
      - CONTIFLOW_STEP=
    command: python run.py
volumes:
  workdir: